### PR TITLE
added JDownloader support

### PR DESCRIPTION
**Pull request by siamak2**

### CODE REVIEW

**Review by pouriap — APPROVED** [review]
Nice

**Comment by siamak2** [comment]
thanks.
when will you release the new xpi?

**Comment by pouriap** [comment]
When I get home today.
I'm also going to send it to mozilla to get signed. So that it can be installed on standard Firefox.

**Comment by pouriap** [comment]
Done: https://github.com/pouriap/Firefox-DownloadGrab/releases/download/v0.11.1a/Download.Grab.v0.11.1a.xpi

**Pull request merged**
